version: v0.10.1
formatter: default
rules:
  - header-min-length
  - header-max-length
  - scope-charset
  - type-enum
severity:
  default: error
settings:
  # body
  body-max-length:
    argument: -1
  body-max-line-length:
    argument: 72
  body-min-length:
    argument: 0
  # footer
  footer-max-length:
    argument: -1
  footer-max-line-length:
    argument: 72
  footer-min-length:
    argument: 0
  footer-enum:
    argument: []
  footer-type-enum:
    argument: []
  # description
  description-max-length:
    argument: -1
  description-min-length:
    argument: 0
  # header
  header-max-length:
    argument: 100
  header-min-length:
    argument: 10
  # scope
  scope-charset:
    argument: BRAZ-0123456789,
  scope-enum:
    argument: []
    flags:
      allow-empty: true
  scope-max-length:
    argument: -1
  scope-min-length:
    argument: 6
  # type
  type-charset:
    argument: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  type-enum:
    argument:
      - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert
  type-max-length:
    argument: -1
  type-min-length:
    argument: 0
