version: '3'

services:
  braz_databases:
    image: mongo:6.0.13-jammy
    container_name: braz_databases
    healthcheck:
      test: |
        echo 'db.runCommand("ping").ok' | mongosh "mongodb://localhost:27017" \
          -u root \
          -p root \
          --authenticationDatabase admin \
          --authenticationMechanism SCRAM-SHA-1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: users,carts,stock,purchases,dashboard
    command: mongod --quiet --logpath /dev/null

  braz_user_microservice:
    image: golang:1.21.6-bullseye
    depends_on: ["braz_databases"]
    container_name: braz_user_microservice
    healthcheck:
      test: |
        curl -f http://localhost:3000/health
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports: ["3000:3000"]
    volumes: [".:/app"]
    environment:
      DB_URI: "mongodb://root:root@braz_databases:27017/"
      DB_NAME: "users"
    working_dir: /app
    command: bash -c 'export SERVICE_FOLDER=users && make local_docker_cmd'
    
