// Code generated by MockGen. DO NOT EDIT.
// Source: packages/database/crud_repository.go
//
// Generated by this command:
//
//	mockgen -source=packages/database/crud_repository.go -destination=services/users/mocks/crud_repository_interface_mock.go -package=mocks -write_generate_directive
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -source=packages/database/crud_repository.go -destination=services/users/mocks/crud_repository_interface_mock.go -package=mocks -write_generate_directive

// MockCrudRepositoryInterface is a mock of CrudRepositoryInterface interface.
type MockCrudRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCrudRepositoryInterfaceMockRecorder
}

// MockCrudRepositoryInterfaceMockRecorder is the mock recorder for MockCrudRepositoryInterface.
type MockCrudRepositoryInterfaceMockRecorder struct {
	mock *MockCrudRepositoryInterface
}

// NewMockCrudRepositoryInterface creates a new mock instance.
func NewMockCrudRepositoryInterface(ctrl *gomock.Controller) *MockCrudRepositoryInterface {
	mock := &MockCrudRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockCrudRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCrudRepositoryInterface) EXPECT() *MockCrudRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateOne mocks base method.
func (m *MockCrudRepositoryInterface) CreateOne(collection string, structure any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOne", collection, structure)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOne indicates an expected call of CreateOne.
func (mr *MockCrudRepositoryInterfaceMockRecorder) CreateOne(collection, structure any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOne", reflect.TypeOf((*MockCrudRepositoryInterface)(nil).CreateOne), collection, structure)
}

// DeleteById mocks base method.
func (m *MockCrudRepositoryInterface) DeleteById(collection, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", collection, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockCrudRepositoryInterfaceMockRecorder) DeleteById(collection, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockCrudRepositoryInterface)(nil).DeleteById), collection, id)
}

// GetById mocks base method.
func (m *MockCrudRepositoryInterface) GetById(collection, id string, structure any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", collection, id, structure)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetById indicates an expected call of GetById.
func (mr *MockCrudRepositoryInterfaceMockRecorder) GetById(collection, id, structure any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockCrudRepositoryInterface)(nil).GetById), collection, id, structure)
}

// UpdateById mocks base method.
func (m *MockCrudRepositoryInterface) UpdateById(collection, id string, structure any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateById", collection, id, structure)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateById indicates an expected call of UpdateById.
func (mr *MockCrudRepositoryInterfaceMockRecorder) UpdateById(collection, id, structure any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateById", reflect.TypeOf((*MockCrudRepositoryInterface)(nil).UpdateById), collection, id, structure)
}
