// Code generated by MockGen. DO NOT EDIT.
// Source: services/users/app/delete_user_by_id.go
//
// Generated by this command:
//
//	mockgen -source=services/users/app/delete_user_by_id.go -destination=services/users/mocks/delete_user_by_id_interface_mock.go -package=mocks -write_generate_directive
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -source=services/users/app/delete_user_by_id.go -destination=services/users/mocks/delete_user_by_id_interface_mock.go -package=mocks -write_generate_directive

// MockDeleteUserByIdInterface is a mock of DeleteUserByIdInterface interface.
type MockDeleteUserByIdInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteUserByIdInterfaceMockRecorder
}

// MockDeleteUserByIdInterfaceMockRecorder is the mock recorder for MockDeleteUserByIdInterface.
type MockDeleteUserByIdInterfaceMockRecorder struct {
	mock *MockDeleteUserByIdInterface
}

// NewMockDeleteUserByIdInterface creates a new mock instance.
func NewMockDeleteUserByIdInterface(ctrl *gomock.Controller) *MockDeleteUserByIdInterface {
	mock := &MockDeleteUserByIdInterface{ctrl: ctrl}
	mock.recorder = &MockDeleteUserByIdInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteUserByIdInterface) EXPECT() *MockDeleteUserByIdInterfaceMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockDeleteUserByIdInterface) Do(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockDeleteUserByIdInterfaceMockRecorder) Do(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockDeleteUserByIdInterface)(nil).Do), id)
}
