// Code generated by MockGen. DO NOT EDIT.
// Source: services/users/app/get_user_paginated.go
//
// Generated by this command:
//
//	mockgen -source=services/users/app/get_user_paginated.go -destination=services/users/mocks/get_user_paginated_interface_mock.go -package=mocks -write_generate_directive
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	database "github.com/italoservio/braz_ecommerce/packages/database"
	app "github.com/italoservio/braz_ecommerce/services/users/app"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -source=services/users/app/get_user_paginated.go -destination=services/users/mocks/get_user_paginated_interface_mock.go -package=mocks -write_generate_directive

// MockGetUserPaginatedInterface is a mock of GetUserPaginatedInterface interface.
type MockGetUserPaginatedInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserPaginatedInterfaceMockRecorder
}

// MockGetUserPaginatedInterfaceMockRecorder is the mock recorder for MockGetUserPaginatedInterface.
type MockGetUserPaginatedInterfaceMockRecorder struct {
	mock *MockGetUserPaginatedInterface
}

// NewMockGetUserPaginatedInterface creates a new mock instance.
func NewMockGetUserPaginatedInterface(ctrl *gomock.Controller) *MockGetUserPaginatedInterface {
	mock := &MockGetUserPaginatedInterface{ctrl: ctrl}
	mock.recorder = &MockGetUserPaginatedInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUserPaginatedInterface) EXPECT() *MockGetUserPaginatedInterfaceMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockGetUserPaginatedInterface) Do(ctx context.Context, input *app.GetUserPaginatedInput) (*database.PaginatedSlice[app.GetUserPaginatedOutput], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, input)
	ret0, _ := ret[0].(*database.PaginatedSlice[app.GetUserPaginatedOutput])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockGetUserPaginatedInterfaceMockRecorder) Do(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockGetUserPaginatedInterface)(nil).Do), ctx, input)
}
